name: Abuntu
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Abuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build Docker-image
        run: bin/build
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: alexvnilsson/abuntu
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}